services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080

    environment:
      DB_USER: postgres
      DB_PWD: bT0mNvhy49F2J6tTrDPd
      DB_HOST: bia.c2jemky4srwo.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      
